description: 'KAO is a student organization for all aviation enthusiasts. Aside from exciting guest speakers and aviation facility tours, our weekly meetings will include discussions of fascinating, advanced topics in the field of aviation, with a special interest to air traffic controllers.'

# configuration required for some pages
domain: www.kentstateatc.org